export type QuestionType = 'batchim' | 'word-choice' | 'sentence' | 'fix-spelling' | 'image' | 'audio';

export type BatchimQuestion = {
  id: string;
  world: number;
  stage: number;
  type: QuestionType;
  prompt: string;
  answer: string;
  choices: string[];
  hint?: string;
  word?: string;
  stem?: string;
  correctSentence?: string;
  imageHint?: string;
  audioSrc?: string;
  audioText?: string;
};

export const questions: BatchimQuestion[] = [
  {
    id: "1-1-01",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "산",
    stem: "사",
    prompt: "높고 큰 땅을 무엇이라고 할까요?",
    answer: "ㄴ",
    choices: ["ㄱ", "ㄴ", "ㄹ"],
    hint: "등산할 때 올라가요."
  },
  {
    id: "1-1-02",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "눈",
    stem: "누",
    prompt: "겨울에 하늘에서 하얗게 내려요.",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "눈사람을 만들 수 있어요."
  },
  {
    id: "1-1-03",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "문",
    stem: "무",
    prompt: "방에 들어갈 때 열고 닫아요.",
    answer: "ㄴ",
    choices: ["ㄱ", "ㄴ", "ㅁ"],
    hint: "손잡이가 있어요."
  },
  {
    id: "1-1-04",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "손",
    stem: "소",
    prompt: "연필을 잡을 때 사용하는 몸의 부분은?",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅇ"],
    hint: "손가락이 있어요."
  },
  {
    id: "1-1-05",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "돈",
    stem: "도",
    prompt: "물건을 살 때 내는 것은?",
    answer: "ㄴ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "동전과 지폐가 있어요."
  },
  {
    id: "1-1-06",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "신",
    stem: "시",
    prompt: "발에 신고 다니는 것은?",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "운동화도 이것의 한 종류예요."
  },
  {
    id: "1-1-07",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "반",
    stem: "바",
    prompt: "학교에서 2학년 3__처럼 부르는 말은?",
    answer: "ㄴ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "친구들과 함께 공부하는 모둠이에요."
  },
  {
    id: "1-1-08",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "선",
    stem: "서",
    prompt: "자를 대고 곧게 그을 수 있어요.",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅇ"],
    hint: "점과 점을 이어 그려요."
  },
  {
    id: "1-1-09",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "산",
    stem: "사",
    prompt: "주말에 가족과 등__을 갔어요.",
    answer: "ㄴ",
    choices: ["ㄱ", "ㄴ", "ㅁ"],
    hint: "높은 곳에 올라가요."
  },
  {
    id: "1-1-10",
    world: 1,
    stage: 1,
    type: "batchim",
    word: "문",
    stem: "무",
    prompt: "교실 __을 조용히 닫았어요.",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅂ"],
    hint: "출입할 때 여닫아요."
  },
  {
    id: "1-2-01",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "달",
    stem: "다",
    prompt: "밤하늘에 둥글게 떠 있어요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "보름에는 아주 둥글어요."
  },
  {
    id: "1-2-02",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "별",
    stem: "벼",
    prompt: "밤하늘에서 반짝반짝 빛나요.",
    answer: "ㄹ",
    choices: ["ㄹ", "ㅁ", "ㅇ"],
    hint: "하늘에 아주 많이 보여요."
  },
  {
    id: "1-2-03",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "물",
    stem: "무",
    prompt: "목이 마를 때 마셔요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "투명하고 시원해요."
  },
  {
    id: "1-2-04",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "길",
    stem: "기",
    prompt: "학교에 갈 때 따라 걷는 곳은?",
    answer: "ㄹ",
    choices: ["ㄱ", "ㄹ", "ㅁ"],
    hint: "자동차도 이곳으로 다녀요."
  },
  {
    id: "1-2-05",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "불",
    stem: "부",
    prompt: "어두울 때 켜는 __빛의 첫 글자는?",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅂ"],
    hint: "전등을 켜면 밝아져요."
  },
  {
    id: "1-2-06",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "귤",
    stem: "규",
    prompt: "겨울에 많이 먹는 주황색 과일은?",
    answer: "ㄹ",
    choices: ["ㄹ", "ㅁ", "ㅇ"],
    hint: "껍질을 벗겨 먹어요."
  },
  {
    id: "1-2-07",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "돌",
    stem: "도",
    prompt: "길가에서 볼 수 있는 단단한 것은?",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "바위보다 작은 경우가 많아요."
  },
  {
    id: "1-2-08",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "발",
    stem: "바",
    prompt: "신발을 신는 몸의 부분은?",
    answer: "ㄹ",
    choices: ["ㄹ", "ㅁ", "ㅇ"],
    hint: "걸을 때 사용해요."
  },
  {
    id: "1-2-09",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "솔",
    stem: "소",
    prompt: "이를 닦는 칫__의 마지막 글자는?",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅇ"],
    hint: "칫솔이라고 해요."
  },
  {
    id: "1-2-10",
    world: 1,
    stage: 2,
    type: "batchim",
    word: "달",
    stem: "다",
    prompt: "오늘 밤에는 __이 밝게 떠 있어요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅂ"],
    hint: "밤하늘을 보세요."
  },
  {
    id: "1-3-01",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "밤",
    stem: "바",
    prompt: "해가 지고 어두워진 때는?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "낮의 반대예요."
  },
  {
    id: "1-3-02",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "곰",
    stem: "고",
    prompt: "몸집이 크고 겨울잠을 자는 동물은?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "꿀을 좋아하는 모습으로 자주 나와요."
  },
  {
    id: "1-3-03",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "감",
    stem: "가",
    prompt: "가을에 먹는 주황색 과일은?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "홍시가 되기도 해요."
  },
  {
    id: "1-3-04",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "봄",
    stem: "보",
    prompt: "꽃이 피기 시작하는 계절은?",
    answer: "ㅁ",
    choices: ["ㄹ", "ㅁ", "ㅇ"],
    hint: "겨울 다음 계절이에요."
  },
  {
    id: "1-3-05",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "몸",
    stem: "모",
    prompt: "머리, 팔, 다리를 모두 합쳐 무엇이라 할까요?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "우리의 신체 전체를 말해요."
  },
  {
    id: "1-3-06",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "힘",
    stem: "히",
    prompt: "무거운 물건을 들 때 필요한 것은?",
    answer: "ㅁ",
    choices: ["ㅁ", "ㅂ", "ㅇ"],
    hint: "힘을 줘서 들어요."
  },
  {
    id: "1-3-07",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "섬",
    stem: "서",
    prompt: "사방이 물로 둘러싸인 땅은?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "제주도도 큰 섬이에요."
  },
  {
    id: "1-3-08",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "꿈",
    stem: "꾸",
    prompt: "잠을 잘 때 꾸는 것은?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "재미있는 장면이 떠오르기도 해요."
  },
  {
    id: "1-3-09",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "밤",
    stem: "바",
    prompt: "__에는 별이 보여요.",
    answer: "ㅁ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "해가 진 뒤예요."
  },
  {
    id: "1-3-10",
    world: 1,
    stage: 3,
    type: "batchim",
    word: "봄",
    stem: "보",
    prompt: "__이 오면 꽃이 피어요.",
    answer: "ㅁ",
    choices: ["ㅁ", "ㅂ", "ㅇ"],
    hint: "따뜻해지는 계절이에요."
  },
  {
    id: "1-4-01",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "밥",
    stem: "바",
    prompt: "식사할 때 먹는 것은?",
    answer: "ㅂ",
    choices: ["ㅁ", "ㅂ", "ㅇ"],
    hint: "쌀로 지어요."
  },
  {
    id: "1-4-02",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "집",
    stem: "지",
    prompt: "가족과 함께 사는 곳은?",
    answer: "ㅂ",
    choices: ["ㄱ", "ㅂ", "ㅇ"],
    hint: "학교가 끝나면 돌아가요."
  },
  {
    id: "1-4-03",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "공",
    stem: "고",
    prompt: "축구나 피구를 할 때 사용하는 것은?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅂ", "ㅇ"],
    hint: "둥글어요."
  },
  {
    id: "1-4-04",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "방",
    stem: "바",
    prompt: "집 안에서 자거나 공부하는 공간은?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "내 방이라고 말해요."
  },
  {
    id: "1-4-05",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "입",
    stem: "이",
    prompt: "음식을 먹을 때 사용하는 몸의 부분은?",
    answer: "ㅂ",
    choices: ["ㅂ", "ㅁ", "ㅇ"],
    hint: "말할 때도 사용해요."
  },
  {
    id: "1-4-06",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "강",
    stem: "가",
    prompt: "물이 길게 흐르는 곳은?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "한강처럼 흐르는 물길이에요."
  },
  {
    id: "1-4-07",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "컵",
    stem: "커",
    prompt: "물을 따라 마시는 그릇은?",
    answer: "ㅂ",
    choices: ["ㅂ", "ㅍ", "ㅇ"],
    hint: "손잡이가 있는 것도 있어요."
  },
  {
    id: "1-4-08",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "빵",
    stem: "빠",
    prompt: "빵집에서 살 수 있는 음식은?",
    answer: "ㅇ",
    choices: ["ㅁ", "ㅂ", "ㅇ"],
    hint: "식빵, 단팥빵이 있어요."
  },
  {
    id: "1-4-09",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "숲",
    stem: "수",
    prompt: "나무가 아주 많이 모여 있는 곳은?",
    answer: "ㅂ",
    choices: ["ㅂ", "ㅍ", "ㅇ"],
    hint: "산에 많이 있어요."
  },
  {
    id: "1-4-10",
    world: 1,
    stage: 4,
    type: "batchim",
    word: "콩",
    stem: "코",
    prompt: "두부를 만들 때 쓰는 작은 알곡은?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "콩밥에도 들어가요."
  },
  {
    id: "1-5-01",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "산",
    stem: "사",
    prompt: "높은 땅을 무엇이라고 할까요?",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "등산을 가요."
  },
  {
    id: "1-5-02",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "달",
    stem: "다",
    prompt: "밤하늘에 떠 있어요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "보름달이 있어요."
  },
  {
    id: "1-5-03",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "밤",
    stem: "바",
    prompt: "낮의 반대는?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "별이 보이는 때예요."
  },
  {
    id: "1-5-04",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "밥",
    stem: "바",
    prompt: "쌀로 지어 먹는 음식은?",
    answer: "ㅂ",
    choices: ["ㅁ", "ㅂ", "ㅇ", "ㄹ"],
    hint: "식사 때 먹어요."
  },
  {
    id: "1-5-05",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "공",
    stem: "고",
    prompt: "축구할 때 차는 것은?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅂ", "ㅇ"],
    hint: "둥글어요."
  },
  {
    id: "1-5-06",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "별",
    stem: "벼",
    prompt: "밤하늘에서 반짝이는 것은?",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "달 옆에서도 보여요."
  },
  {
    id: "1-5-07",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "곰",
    stem: "고",
    prompt: "겨울잠을 자는 큰 동물은?",
    answer: "ㅁ",
    choices: ["ㄴ", "ㅁ", "ㅂ", "ㅇ"],
    hint: "곰이에요."
  },
  {
    id: "1-5-08",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "문",
    stem: "무",
    prompt: "방에 들어갈 때 열어요.",
    answer: "ㄴ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅂ"],
    hint: "손잡이가 있어요."
  },
  {
    id: "1-5-09",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "집",
    stem: "지",
    prompt: "가족과 사는 곳은?",
    answer: "ㅂ",
    choices: ["ㄴ", "ㅁ", "ㅂ", "ㅇ"],
    hint: "학교가 끝나면 돌아가요."
  },
  {
    id: "1-5-10",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "물",
    stem: "무",
    prompt: "목이 마를 때 마셔요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "시원하게 마셔요."
  },
  {
    id: "1-5-11",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "강",
    stem: "가",
    prompt: "물이 길게 흐르는 곳을 무엇이라고 할까요?",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅇ", "ㅂ"],
    hint: "한강처럼 흐르는 물길이에요."
  },
  {
    id: "1-5-12",
    world: 1,
    stage: 5,
    type: "batchim",
    word: "발",
    stem: "바",
    prompt: "신발을 신는 몸의 부분은?",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ", "ㅇ"],
    hint: "걸을 때 사용해요."
  },
  {
    id: "2-1-01",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "옷",
    prompt: "몸에 입는 것을 고르세요.",
    answer: "옷",
    choices: ["옷", "옺", "옻"],
    hint: "ㅅ 받침이에요."
  },
  {
    id: "2-1-02",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "낮",
    prompt: "해가 떠 있는 밝은 시간을 고르세요.",
    answer: "낮",
    choices: ["낫", "낮", "낯"],
    hint: "낮과 밤을 생각해 보세요."
  },
  {
    id: "2-1-03",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "맛",
    prompt: "음식의 느낌을 나타내는 말을 고르세요.",
    answer: "맛",
    choices: ["맛", "맞", "맡"],
    hint: "맛있다의 '맛'이에요."
  },
  {
    id: "2-1-04",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "빗",
    prompt: "머리를 정리할 때 쓰는 물건은?",
    answer: "빗",
    choices: ["빗", "빛", "빚"],
    hint: "빗으로 머리를 빗어요."
  },
  {
    id: "2-1-05",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "젖",
    prompt: "아기가 먹는 엄마의 젖을 고르세요.",
    answer: "젖",
    choices: ["젓", "젖", "젗"],
    hint: "ㅈ 받침이에요."
  },
  {
    id: "2-1-06",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "곶",
    prompt: "바다 쪽으로 뾰족하게 나온 땅을 고르세요.",
    answer: "곶",
    choices: ["곳", "곶", "곷"],
    hint: "지리에서 배우는 말이에요."
  },
  {
    id: "2-1-07",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "숯",
    prompt: "나무를 태워 만든 검은 연료는?",
    answer: "숯",
    choices: ["숫", "숯", "숮"],
    hint: "숯불구이에 쓰여요."
  },
  {
    id: "2-1-08",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "낫",
    prompt: "풀을 베는 농기구를 고르세요.",
    answer: "낫",
    choices: ["낫", "낮", "낯"],
    hint: "낫으로 풀을 베어요."
  },
  {
    id: "2-1-09",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "곳",
    prompt: "장소를 뜻하는 말을 고르세요.",
    answer: "곳",
    choices: ["곳", "곶", "곷"],
    hint: "좋은 곳이라고 말해요."
  },
  {
    id: "2-1-10",
    world: 2,
    stage: 1,
    type: "word-choice",
    word: "빚",
    prompt: "남에게 갚아야 할 돈을 뜻하는 말을 고르세요.",
    answer: "빚",
    choices: ["빗", "빛", "빚"],
    hint: "빚을 갚다라고 해요."
  },
  {
    id: "2-2-01",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "빛",
    prompt: "어둠을 밝히는 것을 고르세요.",
    answer: "빛",
    choices: ["빗", "빛", "빚"],
    hint: "햇빛, 달빛이라고 해요."
  },
  {
    id: "2-2-02",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "꽃",
    prompt: "봄에 피는 예쁜 것을 고르세요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "ㅊ 받침이에요."
  },
  {
    id: "2-2-03",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "낯",
    prompt: "사람의 얼굴을 뜻하는 말을 고르세요.",
    answer: "낯",
    choices: ["낫", "낮", "낯"],
    hint: "낯이 익다라고 말해요."
  },
  {
    id: "2-2-04",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "빚",
    prompt: "갚아야 할 돈을 고르세요.",
    answer: "빚",
    choices: ["빗", "빛", "빚"],
    hint: "ㅈ 받침이에요."
  },
  {
    id: "2-2-05",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "꽃",
    prompt: "화분에 예쁜 __이 피었어요.",
    answer: "꽃",
    choices: ["꽃", "꼿", "꼳"],
    hint: "꽃이 피다."
  },
  {
    id: "2-2-06",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "빛",
    prompt: "창문으로 햇__이 들어와요.",
    answer: "빛",
    choices: ["빛", "빗", "빚"],
    hint: "햇빛이라고 해요."
  },
  {
    id: "2-2-07",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "낮",
    prompt: "__에는 해가 떠 있어요.",
    answer: "낮",
    choices: ["낮", "낫", "낯"],
    hint: "밤의 반대예요."
  },
  {
    id: "2-2-08",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "낯",
    prompt: "처음 보는 사람이라 __이 설어요.",
    answer: "낯",
    choices: ["낯", "낮", "낫"],
    hint: "얼굴이나 익숙함과 관련된 말이에요."
  },
  {
    id: "2-2-09",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "빚",
    prompt: "아빠가 __을 모두 갚았어요.",
    answer: "빚",
    choices: ["빛", "빗", "빚"],
    hint: "돈과 관련된 말이에요."
  },
  {
    id: "2-2-10",
    world: 2,
    stage: 2,
    type: "word-choice",
    word: "꽃",
    prompt: "나비가 __ 위에 앉았어요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "향기가 나요."
  },
  {
    id: "2-3-01",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "밭",
    prompt: "채소를 심는 땅을 고르세요.",
    answer: "밭",
    choices: ["받", "밧", "밭"],
    hint: "ㅌ 받침이에요."
  },
  {
    id: "2-3-02",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "끝",
    prompt: "맨 마지막을 뜻하는 말을 고르세요.",
    answer: "끝",
    choices: ["끋", "끗", "끝"],
    hint: "끝나다의 '끝'이에요."
  },
  {
    id: "2-3-03",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "솥",
    prompt: "밥이나 국을 끓이는 큰 그릇은?",
    answer: "솥",
    choices: ["솟", "솓", "솥"],
    hint: "ㅌ 받침이에요."
  },
  {
    id: "2-3-04",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "곧",
    prompt: "조금 뒤에 바로라는 뜻의 말은?",
    answer: "곧",
    choices: ["곳", "곧", "곹"],
    hint: "곧 갈게라고 해요."
  },
  {
    id: "2-3-05",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "묻",
    prompt: "땅에 씨를 __다. 알맞은 말을 고르세요.",
    answer: "묻",
    choices: ["묻", "뭇", "뭍"],
    hint: "묻다의 '묻'이에요."
  },
  {
    id: "2-3-06",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "밭",
    prompt: "할머니가 __에 상추를 심었어요.",
    answer: "밭",
    choices: ["밧", "받", "밭"],
    hint: "농작물을 심는 곳이에요."
  },
  {
    id: "2-3-07",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "끝",
    prompt: "책을 __까지 읽었어요.",
    answer: "끝",
    choices: ["끝", "끗", "끋"],
    hint: "맨 마지막이에요."
  },
  {
    id: "2-3-08",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "곧",
    prompt: "나는 __ 집에 갈 거예요.",
    answer: "곧",
    choices: ["곳", "곧", "곹"],
    hint: "조금 뒤에 바로라는 뜻이에요."
  },
  {
    id: "2-3-09",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "솥",
    prompt: "할머니가 큰 __에 국을 끓였어요.",
    answer: "솥",
    choices: ["솟", "솥", "솓"],
    hint: "냄비보다 큰 그릇이에요."
  },
  {
    id: "2-3-10",
    world: 2,
    stage: 3,
    type: "word-choice",
    word: "밭",
    prompt: "감자는 __에서 자라요.",
    answer: "밭",
    choices: ["받", "밧", "밭"],
    hint: "채소를 기르는 땅이에요."
  },
  {
    id: "2-4-01",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "앞",
    prompt: "뒤의 반대말을 고르세요.",
    answer: "앞",
    choices: ["압", "앞", "앟"],
    hint: "ㅍ 받침이에요."
  },
  {
    id: "2-4-02",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "잎",
    prompt: "나무에 달린 초록색 부분은?",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나뭇잎이라고 해요."
  },
  {
    id: "2-4-03",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "숲",
    prompt: "나무가 많이 모여 있는 곳은?",
    answer: "숲",
    choices: ["숩", "숲", "숫"],
    hint: "ㅍ 받침이에요."
  },
  {
    id: "2-4-04",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "옆",
    prompt: "왼쪽이나 오른쪽 가까운 곳을 뜻하는 말은?",
    answer: "옆",
    choices: ["엽", "옆", "옇"],
    hint: "내 옆에 앉다."
  },
  {
    id: "2-4-05",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "입",
    prompt: "음식을 먹는 몸의 부분은?",
    answer: "입",
    choices: ["입", "잎", "잇"],
    hint: "ㅂ 받침이에요."
  },
  {
    id: "2-4-06",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "앞",
    prompt: "교실 __에 선생님이 계세요.",
    answer: "앞",
    choices: ["앞", "압", "앗"],
    hint: "뒤의 반대예요."
  },
  {
    id: "2-4-07",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "잎",
    prompt: "가을이 되자 나뭇__이 떨어졌어요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무에 달린 부분이에요."
  },
  {
    id: "2-4-08",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "옆",
    prompt: "친구가 내 __에 앉았어요.",
    answer: "옆",
    choices: ["엽", "옆", "엣"],
    hint: "바로 가까운 쪽이에요."
  },
  {
    id: "2-4-09",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "숲",
    prompt: "새들이 __에서 노래해요.",
    answer: "숲",
    choices: ["숩", "숲", "숫"],
    hint: "나무가 많아요."
  },
  {
    id: "2-4-10",
    world: 2,
    stage: 4,
    type: "word-choice",
    word: "입",
    prompt: "밥을 먹기 전에 __을 크게 벌렸어요.",
    answer: "입",
    choices: ["잎", "입", "잇"],
    hint: "먹고 말하는 곳이에요."
  },
  {
    id: "2-5-01",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "옷",
    prompt: "몸에 입는 것을 고르세요.",
    answer: "옷",
    choices: ["옷", "옺", "옻", "옽"],
    hint: "ㅅ 받침이에요."
  },
  {
    id: "2-5-02",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "낮",
    prompt: "해가 떠 있는 시간을 고르세요.",
    answer: "낮",
    choices: ["낫", "낮", "낯", "낱"],
    hint: "밤의 반대예요."
  },
  {
    id: "2-5-03",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "빛",
    prompt: "햇__이 창문으로 들어와요.",
    answer: "빛",
    choices: ["빗", "빛", "빚", "빋"],
    hint: "밝게 비추는 것이에요."
  },
  {
    id: "2-5-04",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "꽃",
    prompt: "나비가 앉는 예쁜 식물의 부분은?",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳", "꼻"],
    hint: "향기가 나요."
  },
  {
    id: "2-5-05",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "밭",
    prompt: "채소를 심는 곳은?",
    answer: "밭",
    choices: ["받", "밧", "밭", "밪"],
    hint: "ㅌ 받침이에요."
  },
  {
    id: "2-5-06",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "앞",
    prompt: "뒤의 반대말은?",
    answer: "앞",
    choices: ["압", "앞", "앗", "앟"],
    hint: "ㅍ 받침이에요."
  },
  {
    id: "2-5-07",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "잎",
    prompt: "나무에 달린 초록색 부분은?",
    answer: "잎",
    choices: ["입", "잎", "잇", "잊"],
    hint: "나뭇잎이에요."
  },
  {
    id: "2-5-08",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "끝",
    prompt: "맨 마지막을 뜻하는 말은?",
    answer: "끝",
    choices: ["끋", "끗", "끝", "끛"],
    hint: "끝나다의 '끝'이에요."
  },
  {
    id: "2-5-09",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "빚",
    prompt: "남에게 갚아야 하는 돈은?",
    answer: "빚",
    choices: ["빗", "빛", "빚", "빝"],
    hint: "빚을 갚다."
  },
  {
    id: "2-5-10",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "낫",
    prompt: "풀을 베는 농기구는?",
    answer: "낫",
    choices: ["낫", "낮", "낯", "낱"],
    hint: "농촌에서 볼 수 있어요."
  },
  {
    id: "2-5-11",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "숯",
    prompt: "불을 피울 때 쓰는 검은 연료를 고르세요.",
    answer: "숯",
    choices: ["숫", "숯", "숮", "숟"],
    hint: "숯불구이에 쓰여요."
  },
  {
    id: "2-5-12",
    world: 2,
    stage: 5,
    type: "word-choice",
    word: "옆",
    prompt: "친구가 내 __에 앉았어요. 알맞은 말을 고르세요.",
    answer: "옆",
    choices: ["엽", "옆", "엣", "엎"],
    hint: "바로 가까운 쪽이에요."
  },
  {
    id: "3-1-01",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "낮",
    prompt: "__에는 해가 밝게 떠 있어요.",
    answer: "낮",
    choices: ["낫", "낮", "낯"],
    hint: "밤의 반대예요."
  },
  {
    id: "3-1-02",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "옷",
    prompt: "추워서 두꺼운 __을 입었어요.",
    answer: "옷",
    choices: ["옷", "옺", "옻"],
    hint: "몸에 입어요."
  },
  {
    id: "3-1-03",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "밭",
    prompt: "할아버지가 __에 고추를 심었어요.",
    answer: "밭",
    choices: ["받", "밧", "밭"],
    hint: "채소를 심는 곳이에요."
  },
  {
    id: "3-1-04",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "빛",
    prompt: "창문으로 햇__이 들어와요.",
    answer: "빛",
    choices: ["빗", "빛", "빚"],
    hint: "밝게 비추는 것이에요."
  },
  {
    id: "3-1-05",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "앞",
    prompt: "학교 __에서 친구를 만났어요.",
    answer: "앞",
    choices: ["압", "앞", "앗"],
    hint: "건물의 앞쪽이에요."
  },
  {
    id: "3-1-06",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "꽃",
    prompt: "화단에 예쁜 __이 피었어요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "향기가 나요."
  },
  {
    id: "3-1-07",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "잎",
    prompt: "가을이 되자 나뭇__이 노랗게 변했어요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무에 달려 있어요."
  },
  {
    id: "3-1-08",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "끝",
    prompt: "책을 처음부터 __까지 읽었어요.",
    answer: "끝",
    choices: ["끋", "끗", "끝"],
    hint: "맨 마지막이에요."
  },
  {
    id: "3-1-09",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "숲",
    prompt: "다람쥐가 __속을 뛰어다녀요.",
    answer: "숲",
    choices: ["숩", "숲", "숫"],
    hint: "나무가 아주 많아요."
  },
  {
    id: "3-1-10",
    world: 3,
    stage: 1,
    type: "sentence",
    word: "곧",
    prompt: "수업이 __ 시작해요.",
    answer: "곧",
    choices: ["곳", "곧", "곹"],
    hint: "조금 뒤에 바로라는 뜻이에요."
  },
  {
    id: "3-2-01",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "공",
    prompt: "운동장에서 __을 던지며 놀았어요.",
    answer: "공",
    choices: ["곰", "공", "곤"],
    hint: "둥근 운동 도구예요."
  },
  {
    id: "3-2-02",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "문",
    prompt: "교실 __을 조용히 닫았어요.",
    answer: "문",
    choices: ["문", "물", "뭄"],
    hint: "출입할 때 여닫아요."
  },
  {
    id: "3-2-03",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "달",
    prompt: "밤하늘에 둥근 __이 떴어요.",
    answer: "달",
    choices: ["단", "달", "담"],
    hint: "보름에는 아주 둥글어요."
  },
  {
    id: "3-2-04",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "별",
    prompt: "밤하늘에 __이 반짝여요.",
    answer: "별",
    choices: ["변", "별", "벼"],
    hint: "작은 빛처럼 보여요."
  },
  {
    id: "3-2-05",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "밥",
    prompt: "아침 __을 맛있게 먹었어요.",
    answer: "밥",
    choices: ["밤", "밥", "방"],
    hint: "식사예요."
  },
  {
    id: "3-2-06",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "방",
    prompt: "내 __을 깨끗이 정리했어요.",
    answer: "방",
    choices: ["반", "밤", "방"],
    hint: "집 안의 공간이에요."
  },
  {
    id: "3-2-07",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "감",
    prompt: "가을에 달콤한 __을 먹었어요.",
    answer: "감",
    choices: ["간", "감", "강"],
    hint: "주황색 과일이에요."
  },
  {
    id: "3-2-08",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "물",
    prompt: "운동을 하고 시원한 __을 마셨어요.",
    answer: "물",
    choices: ["문", "물", "뭄"],
    hint: "목이 마를 때 마셔요."
  },
  {
    id: "3-2-09",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "집",
    prompt: "학교가 끝나고 __에 갔어요.",
    answer: "집",
    choices: ["짐", "집", "징"],
    hint: "가족과 사는 곳이에요."
  },
  {
    id: "3-2-10",
    world: 3,
    stage: 2,
    type: "sentence",
    word: "봄",
    prompt: "__이 되면 꽃이 피어요.",
    answer: "봄",
    choices: ["본", "볼", "봄"],
    hint: "겨울 다음 계절이에요."
  },
  {
    id: "3-3-01",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "낮",
    prompt: "__에는 해가 떠 있어요.",
    answer: "낮",
    choices: ["낮", "낫"],
    hint: "시간을 뜻해요."
  },
  {
    id: "3-3-02",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "낫",
    prompt: "농부가 __으로 풀을 베었어요.",
    answer: "낫",
    choices: ["낮", "낫"],
    hint: "도구를 뜻해요."
  },
  {
    id: "3-3-03",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "빛",
    prompt: "햇__이 따뜻해요.",
    answer: "빛",
    choices: ["빛", "빗"],
    hint: "밝게 비추는 것이에요."
  },
  {
    id: "3-3-04",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "빗",
    prompt: "__으로 머리를 정리했어요.",
    answer: "빗",
    choices: ["빛", "빗"],
    hint: "머리카락을 빗어요."
  },
  {
    id: "3-3-05",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "입",
    prompt: "밥을 먹으려고 __을 벌렸어요.",
    answer: "입",
    choices: ["입", "잎"],
    hint: "몸의 부분이에요."
  },
  {
    id: "3-3-06",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "잎",
    prompt: "나뭇__이 바람에 흔들려요.",
    answer: "잎",
    choices: ["입", "잎"],
    hint: "나무의 부분이에요."
  },
  {
    id: "3-3-07",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "곳",
    prompt: "여기는 조용한 __이에요.",
    answer: "곳",
    choices: ["곳", "곶"],
    hint: "장소를 뜻해요."
  },
  {
    id: "3-3-08",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "곶",
    prompt: "바다로 뾰족하게 나온 땅은 __이에요.",
    answer: "곶",
    choices: ["곳", "곶"],
    hint: "지리에서 쓰는 말이에요."
  },
  {
    id: "3-3-09",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "빚",
    prompt: "빌린 돈은 나중에 __을 갚아야 해요.",
    answer: "빚",
    choices: ["빛", "빚"],
    hint: "돈과 관련된 말이에요."
  },
  {
    id: "3-3-10",
    world: 3,
    stage: 3,
    type: "word-choice",
    word: "맛",
    prompt: "이 사탕은 딸기 __이 나요.",
    answer: "맛",
    choices: ["맛", "맞"],
    hint: "음식의 느낌이에요."
  },
  {
    id: "3-4-01",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 사과의 갑이 올랐어요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "물건의 가격을 뜻해요.",
    correctSentence: "사과의 값이 올랐어요."
  },
  {
    id: "3-4-02",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 나는 책을 익고 있어요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고"],
    hint: "책을 보다의 뜻이에요.",
    correctSentence: "나는 책을 읽고 있어요."
  },
  {
    id: "3-4-03",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 친구가 박에서 기다려요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "안의 반대예요.",
    correctSentence: "친구가 밖에서 기다려요."
  },
  {
    id: "3-4-04",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 화단에 꼿이 피었어요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "봄에 피어요.",
    correctSentence: "화단에 꽃이 피었어요."
  },
  {
    id: "3-4-05",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 할머니가 받에 상추를 심었어요.",
    answer: "밭",
    choices: ["받", "밧", "밭"],
    hint: "채소를 심는 땅이에요.",
    correctSentence: "할머니가 밭에 상추를 심었어요."
  },
  {
    id: "3-4-06",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 새 옺을 입었어요.",
    answer: "옷",
    choices: ["옷", "옺", "옻"],
    hint: "몸에 입어요.",
    correctSentence: "새 옷을 입었어요."
  },
  {
    id: "3-4-07",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 낫에는 해가 떠 있어요.",
    answer: "낮",
    choices: ["낫", "낮", "낯"],
    hint: "시간을 뜻해요.",
    correctSentence: "낮에는 해가 떠 있어요."
  },
  {
    id: "3-4-08",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 나뭇입이 떨어졌어요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무의 부분이에요.",
    correctSentence: "나뭇잎이 떨어졌어요."
  },
  {
    id: "3-4-09",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 학교 압에서 만나요.",
    answer: "앞",
    choices: ["압", "앞", "앗"],
    hint: "뒤의 반대예요.",
    correctSentence: "학교 앞에서 만나요."
  },
  {
    id: "3-4-10",
    world: 3,
    stage: 4,
    type: "fix-spelling",
    prompt: "잘못된 말을 바르게 고르세요: 햇빗이 따뜻해요.",
    answer: "빛",
    choices: ["빗", "빛", "빚"],
    hint: "햇빛이라고 써요.",
    correctSentence: "햇빛이 따뜻해요."
  },
  {
    id: "3-5-01",
    world: 3,
    stage: 5,
    type: "sentence",
    word: "낮",
    prompt: "__에는 운동장에서 놀아요.",
    answer: "낮",
    choices: ["낫", "낮", "낯"],
    hint: "밤의 반대예요."
  },
  {
    id: "3-5-02",
    world: 3,
    stage: 5,
    type: "sentence",
    word: "밭",
    prompt: "감자를 __에 심었어요.",
    answer: "밭",
    choices: ["받", "밧", "밭"],
    hint: "농작물을 기르는 땅이에요."
  },
  {
    id: "3-5-03",
    world: 3,
    stage: 5,
    type: "word-choice",
    word: "빛",
    prompt: "전등의 밝은 것을 뜻하는 말은?",
    answer: "빛",
    choices: ["빗", "빛", "빚"],
    hint: "빛이에요."
  },
  {
    id: "3-5-04",
    world: 3,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 나뭇입이 흔들려요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무의 부분이에요.",
    correctSentence: "나뭇잎이 흔들려요."
  },
  {
    id: "3-5-05",
    world: 3,
    stage: 5,
    type: "word-choice",
    word: "앞",
    prompt: "뒤의 반대말은?",
    answer: "앞",
    choices: ["압", "앞", "앗"],
    hint: "학교 앞이라고 해요."
  },
  {
    id: "3-5-06",
    world: 3,
    stage: 5,
    type: "sentence",
    word: "꽃",
    prompt: "벌이 __으로 날아왔어요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "향기가 나요."
  },
  {
    id: "3-5-07",
    world: 3,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 장난감의 갑이 비싸요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요.",
    correctSentence: "장난감의 값이 비싸요."
  },
  {
    id: "3-5-08",
    world: 3,
    stage: 5,
    type: "word-choice",
    word: "끝",
    prompt: "맨 마지막을 뜻하는 말은?",
    answer: "끝",
    choices: ["끋", "끗", "끝"],
    hint: "끝나다의 끝이에요."
  },
  {
    id: "3-5-09",
    world: 3,
    stage: 5,
    type: "sentence",
    word: "숲",
    prompt: "우리는 __길을 걸었어요.",
    answer: "숲",
    choices: ["숩", "숲", "숫"],
    hint: "나무가 많아요."
  },
  {
    id: "3-5-10",
    world: 3,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 박에 비가 와요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "안의 반대예요.",
    correctSentence: "밖에 비가 와요."
  },
  {
    id: "3-5-11",
    world: 3,
    stage: 5,
    type: "sentence",
    word: "곧",
    prompt: "수업이 __ 시작해요.",
    answer: "곧",
    choices: ["곳", "곧", "곹"],
    hint: "조금 뒤에 바로라는 뜻이에요."
  },
  {
    id: "3-5-12",
    world: 3,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 새 옺을 입었어요.",
    answer: "옷",
    choices: ["옷", "옺", "옻"],
    hint: "몸에 입는 것이에요.",
    correctSentence: "새 옷을 입었어요."
  },
  {
    id: "4-1-01",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "밖",
    prompt: "안의 반대말을 고르세요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "ㄲ 받침이에요."
  },
  {
    id: "4-1-02",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "있다",
    prompt: "책상 위에 연필이 __.",
    answer: "있다",
    choices: ["잇다", "있다", "잊다"],
    hint: "ㅆ 받침이에요."
  },
  {
    id: "4-1-03",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "없다",
    prompt: "반대말이 '있다'인 말을 고르세요.",
    answer: "없다",
    choices: ["업다", "없다", "업따"],
    hint: "ㅄ 받침이 들어가요."
  },
  {
    id: "4-1-04",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "갔다",
    prompt: "어제 학교에 __.",
    answer: "갔다",
    choices: ["갓다", "갔다", "갇다"],
    hint: "가다의 과거형이에요."
  },
  {
    id: "4-1-05",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "왔다",
    prompt: "친구가 우리 집에 __.",
    answer: "왔다",
    choices: ["왓다", "왔다", "왇다"],
    hint: "오다의 과거형이에요."
  },
  {
    id: "4-1-06",
    world: 4,
    stage: 1,
    type: "sentence",
    word: "밖",
    prompt: "비가 그쳐서 __에 나갔어요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "안의 반대예요."
  },
  {
    id: "4-1-07",
    world: 4,
    stage: 1,
    type: "sentence",
    word: "있다",
    prompt: "가방 안에 연필이 __.",
    answer: "있다",
    choices: ["잇다", "있다", "잊다"],
    hint: "무언가 존재할 때 써요."
  },
  {
    id: "4-1-08",
    world: 4,
    stage: 1,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 박에서 공을 차요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "집 안이 아니에요.",
    correctSentence: "밖에서 공을 차요."
  },
  {
    id: "4-1-09",
    world: 4,
    stage: 1,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 책이 책상 위에 잇다.",
    answer: "있다",
    choices: ["잇다", "있다", "잊다"],
    hint: "ㅆ 받침이에요.",
    correctSentence: "책이 책상 위에 있다."
  },
  {
    id: "4-1-10",
    world: 4,
    stage: 1,
    type: "word-choice",
    word: "없다",
    prompt: "지우개가 하나도 __.",
    answer: "없다",
    choices: ["업다", "없다", "업따"],
    hint: "있다의 반대말이에요."
  },
  {
    id: "4-2-01",
    world: 4,
    stage: 2,
    type: "word-choice",
    word: "닭",
    prompt: "꼬끼오 하고 우는 동물을 고르세요.",
    answer: "닭",
    choices: ["닥", "닭", "달"],
    hint: "ㄺ 받침이에요."
  },
  {
    id: "4-2-02",
    world: 4,
    stage: 2,
    type: "word-choice",
    word: "읽다",
    prompt: "책을 __. 알맞은 말을 고르세요.",
    answer: "읽다",
    choices: ["익다", "읽다", "일다"],
    hint: "글자를 보고 뜻을 알아요."
  },
  {
    id: "4-2-03",
    world: 4,
    stage: 2,
    type: "word-choice",
    word: "맑다",
    prompt: "하늘에 구름이 적고 깨끗한 상태를 고르세요.",
    answer: "맑다",
    choices: ["막다", "맑다", "말다"],
    hint: "ㄺ 받침이에요."
  },
  {
    id: "4-2-04",
    world: 4,
    stage: 2,
    type: "word-choice",
    word: "밝다",
    prompt: "어둡다의 반대말을 고르세요.",
    answer: "밝다",
    choices: ["박다", "밝다", "발다"],
    hint: "빛이 환한 상태예요."
  },
  {
    id: "4-2-05",
    world: 4,
    stage: 2,
    type: "sentence",
    word: "닭",
    prompt: "__이 알을 낳았어요.",
    answer: "닭",
    choices: ["닥", "닭", "달"],
    hint: "농장에서 볼 수 있어요."
  },
  {
    id: "4-2-06",
    world: 4,
    stage: 2,
    type: "sentence",
    word: "읽다",
    prompt: "나는 매일 책을 __.",
    answer: "읽다",
    choices: ["익다", "읽다", "일다"],
    hint: "책을 보는 행동이에요."
  },
  {
    id: "4-2-07",
    world: 4,
    stage: 2,
    type: "sentence",
    word: "맑다",
    prompt: "오늘 하늘이 아주 __.",
    answer: "맑다",
    choices: ["막다", "맑다", "말다"],
    hint: "구름이 적어요."
  },
  {
    id: "4-2-08",
    world: 4,
    stage: 2,
    type: "sentence",
    word: "밝다",
    prompt: "교실에 불을 켜니 아주 __.",
    answer: "밝다",
    choices: ["박다", "밝다", "발다"],
    hint: "어둡다의 반대예요."
  },
  {
    id: "4-2-09",
    world: 4,
    stage: 2,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 책을 익고 있어요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고"],
    hint: "ㄺ 받침이에요.",
    correctSentence: "책을 읽고 있어요."
  },
  {
    id: "4-2-10",
    world: 4,
    stage: 2,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 오늘은 막은 하늘이에요.",
    answer: "맑은",
    choices: ["막은", "맑은", "말은"],
    hint: "깨끗한 하늘을 뜻해요.",
    correctSentence: "오늘은 맑은 하늘이에요."
  },
  {
    id: "4-3-01",
    world: 4,
    stage: 3,
    type: "word-choice",
    word: "삶",
    prompt: "사람이 살아가는 일을 뜻하는 말을 고르세요.",
    answer: "삶",
    choices: ["삼", "삶", "살"],
    hint: "ㄻ 받침이에요."
  },
  {
    id: "4-3-02",
    world: 4,
    stage: 3,
    type: "word-choice",
    word: "젊다",
    prompt: "나이가 많지 않다는 뜻의 말을 고르세요.",
    answer: "젊다",
    choices: ["점다", "젊다", "절다"],
    hint: "ㄻ 받침이에요."
  },
  {
    id: "4-3-03",
    world: 4,
    stage: 3,
    type: "word-choice",
    word: "넓다",
    prompt: "좁다의 반대말을 고르세요.",
    answer: "넓다",
    choices: ["넙다", "넓다", "널다"],
    hint: "ㄼ 받침이에요."
  },
  {
    id: "4-3-04",
    world: 4,
    stage: 3,
    type: "word-choice",
    word: "짧다",
    prompt: "길다의 반대말을 고르세요.",
    answer: "짧다",
    choices: ["짭다", "짧다", "짤다"],
    hint: "ㄼ 받침이에요."
  },
  {
    id: "4-3-05",
    world: 4,
    stage: 3,
    type: "sentence",
    word: "넓다",
    prompt: "운동장이 아주 __.",
    answer: "넓다",
    choices: ["넙다", "넓다", "널다"],
    hint: "공간이 커요."
  },
  {
    id: "4-3-06",
    world: 4,
    stage: 3,
    type: "sentence",
    word: "짧다",
    prompt: "이 연필은 너무 __.",
    answer: "짧다",
    choices: ["짭다", "짧다", "짤다"],
    hint: "길다의 반대예요."
  },
  {
    id: "4-3-07",
    world: 4,
    stage: 3,
    type: "sentence",
    word: "젊다",
    prompt: "우리 삼촌은 아직 __.",
    answer: "젊다",
    choices: ["점다", "젊다", "절다"],
    hint: "나이가 많지 않아요."
  },
  {
    id: "4-3-08",
    world: 4,
    stage: 3,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 너븐 운동장에서 뛰어요.",
    answer: "넓은",
    choices: ["너븐", "넓은", "널은"],
    hint: "좁은의 반대예요.",
    correctSentence: "넓은 운동장에서 뛰어요."
  },
  {
    id: "4-3-09",
    world: 4,
    stage: 3,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 짜븐 끈을 골랐어요.",
    answer: "짧은",
    choices: ["짜븐", "짧은", "짤은"],
    hint: "길지 않다는 뜻이에요.",
    correctSentence: "짧은 끈을 골랐어요."
  },
  {
    id: "4-3-10",
    world: 4,
    stage: 3,
    type: "word-choice",
    word: "삶",
    prompt: "건강한 __을 위해 운동해요.",
    answer: "삶",
    choices: ["삼", "삶", "살"],
    hint: "살아가는 생활을 뜻해요."
  },
  {
    id: "4-4-01",
    world: 4,
    stage: 4,
    type: "word-choice",
    word: "값",
    prompt: "물건의 가격을 뜻하는 말을 고르세요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "ㅄ 받침이에요."
  },
  {
    id: "4-4-02",
    world: 4,
    stage: 4,
    type: "word-choice",
    word: "몫",
    prompt: "여럿이 나눌 때 자기에게 돌아오는 부분은?",
    answer: "몫",
    choices: ["목", "몫", "못"],
    hint: "ㄳ 받침이에요."
  },
  {
    id: "4-4-03",
    world: 4,
    stage: 4,
    type: "word-choice",
    word: "싫다",
    prompt: "좋다의 반대 느낌을 나타내는 말을 고르세요.",
    answer: "싫다",
    choices: ["실다", "싫다", "싯다"],
    hint: "ㅀ 받침이에요."
  },
  {
    id: "4-4-04",
    world: 4,
    stage: 4,
    type: "word-choice",
    word: "없다",
    prompt: "있다의 반대말은?",
    answer: "없다",
    choices: ["업다", "없다", "업따"],
    hint: "ㅄ 받침이에요."
  },
  {
    id: "4-4-05",
    world: 4,
    stage: 4,
    type: "sentence",
    word: "값",
    prompt: "이 장난감의 __은 만 원이에요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요."
  },
  {
    id: "4-4-06",
    world: 4,
    stage: 4,
    type: "sentence",
    word: "몫",
    prompt: "케이크를 똑같이 나누어 내 __을 받았어요.",
    answer: "몫",
    choices: ["목", "몫", "못"],
    hint: "내가 받을 부분이에요."
  },
  {
    id: "4-4-07",
    world: 4,
    stage: 4,
    type: "sentence",
    word: "싫다",
    prompt: "나는 거짓말이 __.",
    answer: "싫다",
    choices: ["실다", "싫다", "싯다"],
    hint: "좋아하지 않는다는 뜻이에요."
  },
  {
    id: "4-4-08",
    world: 4,
    stage: 4,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 연필의 갑이 올랐어요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요.",
    correctSentence: "연필의 값이 올랐어요."
  },
  {
    id: "4-4-09",
    world: 4,
    stage: 4,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 각자 자기 목을 가져가세요.",
    answer: "몫",
    choices: ["목", "몫", "못"],
    hint: "나누어 받은 부분이에요.",
    correctSentence: "각자 자기 몫을 가져가세요."
  },
  {
    id: "4-4-10",
    world: 4,
    stage: 4,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 저는 거짓말이 실어요.",
    answer: "싫어요",
    choices: ["실어요", "싫어요", "싯어요"],
    hint: "좋아하지 않는다는 뜻이에요.",
    correctSentence: "저는 거짓말이 싫어요."
  },
  {
    id: "4-5-01",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "닭",
    prompt: "꼬끼오 하고 우는 동물은?",
    answer: "닭",
    choices: ["닥", "닭", "달", "닧"],
    hint: "ㄺ 받침이에요."
  },
  {
    id: "4-5-02",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "읽다",
    prompt: "책을 보는 행동을 고르세요.",
    answer: "읽다",
    choices: ["익다", "읽다", "일다", "잃다"],
    hint: "ㄺ 받침이에요."
  },
  {
    id: "4-5-03",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "넓다",
    prompt: "좁다의 반대말은?",
    answer: "넓다",
    choices: ["넙다", "넓다", "널다", "넓따"],
    hint: "ㄼ 받침이에요."
  },
  {
    id: "4-5-04",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "짧다",
    prompt: "길다의 반대말은?",
    answer: "짧다",
    choices: ["짭다", "짧다", "짤다", "짧따"],
    hint: "ㄼ 받침이에요."
  },
  {
    id: "4-5-05",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "값",
    prompt: "물건의 가격을 뜻하는 말은?",
    answer: "값",
    choices: ["갑", "값", "갓", "갚"],
    hint: "ㅄ 받침이에요."
  },
  {
    id: "4-5-06",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "몫",
    prompt: "나누어 받은 자기 부분은?",
    answer: "몫",
    choices: ["목", "몫", "못", "몯"],
    hint: "ㄳ 받침이에요."
  },
  {
    id: "4-5-07",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "싫다",
    prompt: "좋아하지 않는다는 뜻의 말은?",
    answer: "싫다",
    choices: ["실다", "싫다", "싯다", "실타"],
    hint: "ㅀ 받침이에요."
  },
  {
    id: "4-5-08",
    world: 4,
    stage: 5,
    type: "sentence",
    word: "맑다",
    prompt: "비가 그친 뒤 하늘이 아주 __.",
    answer: "맑다",
    choices: ["막다", "맑다", "말다", "맑따"],
    hint: "깨끗하고 환해요."
  },
  {
    id: "4-5-09",
    world: 4,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 나는 동화책을 익고 있어요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고", "잃고"],
    hint: "책을 보는 행동이에요.",
    correctSentence: "나는 동화책을 읽고 있어요."
  },
  {
    id: "4-5-10",
    world: 4,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 너븐 운동장에서 달렸어요.",
    answer: "넓은",
    choices: ["너븐", "넓은", "널은", "넙은"],
    hint: "좁지 않아요.",
    correctSentence: "넓은 운동장에서 달렸어요."
  },
  {
    id: "4-5-11",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "밝다",
    prompt: "어둡다의 반대말을 고르세요.",
    answer: "밝다",
    choices: ["박다", "밝다", "발다", "밝따"],
    hint: "환하고 빛이 있어요."
  },
  {
    id: "4-5-12",
    world: 4,
    stage: 5,
    type: "word-choice",
    word: "맑다",
    prompt: "구름이 적고 깨끗한 하늘을 나타내는 말을 고르세요.",
    answer: "맑다",
    choices: ["막다", "맑다", "말다", "맑따"],
    hint: "ㄺ 받침이에요."
  },
  {
    id: "4-5-13",
    world: 4,
    stage: 5,
    type: "sentence",
    word: "짧다",
    prompt: "이 줄은 너무 __.",
    answer: "짧다",
    choices: ["짭다", "짧다", "짤다", "짧따"],
    hint: "길다의 반대예요."
  },
  {
    id: "4-5-14",
    world: 4,
    stage: 5,
    type: "sentence",
    word: "없다",
    prompt: "가방 안에 지우개가 __.",
    answer: "없다",
    choices: ["업다", "없다", "업따", "엇다"],
    hint: "있다의 반대말이에요."
  },
  {
    id: "4-5-15",
    world: 4,
    stage: 5,
    type: "fix-spelling",
    prompt: "바르게 고르세요: 저는 거짓말이 실어요.",
    answer: "싫어요",
    choices: ["실어요", "싫어요", "싯어요", "실허요"],
    hint: "좋아하지 않는다는 뜻이에요.",
    correctSentence: "저는 거짓말이 싫어요."
  },
  {
    id: "5-1-01",
    world: 5,
    stage: 1,
    type: "image",
    word: "산",
    stem: "사",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㄴ",
    choices: ["ㄱ", "ㄴ", "ㄹ"],
    hint: "등산을 가요.",
    imageHint: "산 그림"
  },
  {
    id: "5-1-02",
    world: 5,
    stage: 1,
    type: "image",
    word: "달",
    stem: "다",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "밤하늘에 떠 있어요.",
    imageHint: "달 그림"
  },
  {
    id: "5-1-03",
    world: 5,
    stage: 1,
    type: "image",
    word: "꽃",
    stem: "꼬",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅊ",
    choices: ["ㅅ", "ㅈ", "ㅊ"],
    hint: "향기가 나요.",
    imageHint: "꽃 그림"
  },
  {
    id: "5-1-04",
    world: 5,
    stage: 1,
    type: "image",
    word: "밭",
    stem: "바",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅌ",
    choices: ["ㄷ", "ㅅ", "ㅌ"],
    hint: "채소를 심어요.",
    imageHint: "밭 그림"
  },
  {
    id: "5-1-05",
    world: 5,
    stage: 1,
    type: "image",
    word: "잎",
    stem: "이",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅍ",
    choices: ["ㅂ", "ㅍ", "ㅅ"],
    hint: "나무에 달려 있어요.",
    imageHint: "나뭇잎 그림"
  },
  {
    id: "5-1-06",
    world: 5,
    stage: 1,
    type: "image",
    word: "닭",
    stem: "다",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㄺ",
    choices: ["ㄱ", "ㄺ", "ㄻ"],
    hint: "꼬끼오 하고 울어요.",
    imageHint: "닭 그림"
  },
  {
    id: "5-1-07",
    world: 5,
    stage: 1,
    type: "image",
    word: "공",
    stem: "고",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅇ",
    choices: ["ㄴ", "ㅁ", "ㅇ"],
    hint: "축구할 때 차요.",
    imageHint: "공 그림"
  },
  {
    id: "5-1-08",
    world: 5,
    stage: 1,
    type: "image",
    word: "숲",
    stem: "수",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅍ",
    choices: ["ㅂ", "ㅍ", "ㅅ"],
    hint: "나무가 아주 많아요.",
    imageHint: "숲 그림"
  },
  {
    id: "5-1-09",
    world: 5,
    stage: 1,
    type: "image",
    word: "별",
    stem: "벼",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㄹ",
    choices: ["ㄴ", "ㄹ", "ㅁ"],
    hint: "밤하늘에서 반짝여요.",
    imageHint: "별 그림"
  },
  {
    id: "5-1-10",
    world: 5,
    stage: 1,
    type: "image",
    word: "값",
    stem: "가",
    prompt: "그림과 가격표를 보고 단어를 완성하세요.",
    answer: "ㅄ",
    choices: ["ㅂ", "ㅄ", "ㅅ"],
    hint: "물건의 가격을 뜻해요.",
    imageHint: "가격표 그림"
  },
  {
    id: "5-2-01",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "밭",
    stem: "바",
    prompt: "꽃이 바_에 피었어요.",
    answer: "ㅌ",
    choices: ["ㄷ", "ㅅ", "ㅈ", "ㅊ", "ㅌ"],
    hint: "채소나 꽃을 심는 땅이에요."
  },
  {
    id: "5-2-02",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "낮",
    stem: "나",
    prompt: "나_에는 해가 떠 있어요.",
    answer: "ㅈ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "밤의 반대예요."
  },
  {
    id: "5-2-03",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "옷",
    stem: "오",
    prompt: "추워서 두꺼운 오_을 입었어요.",
    answer: "ㅅ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "몸에 입어요."
  },
  {
    id: "5-2-04",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "앞",
    stem: "아",
    prompt: "학교 아_에서 친구를 만났어요.",
    answer: "ㅍ",
    choices: ["ㅂ", "ㅍ", "ㅁ", "ㅎ"],
    hint: "뒤의 반대예요."
  },
  {
    id: "5-2-05",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "빛",
    stem: "비",
    prompt: "햇비_이 따뜻해요.",
    answer: "ㅊ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "밝게 비추는 것이에요."
  },
  {
    id: "5-2-06",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "꽃",
    stem: "꼬",
    prompt: "화단에 예쁜 꼬_이 피었어요.",
    answer: "ㅊ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "봄에 많이 보여요."
  },
  {
    id: "5-2-07",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "닭",
    stem: "다",
    prompt: "다_이 마당을 걸어다녀요.",
    answer: "ㄺ",
    choices: ["ㄱ", "ㄺ", "ㄻ", "ㄼ"],
    hint: "꼬끼오 하고 울어요."
  },
  {
    id: "5-2-08",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "값",
    stem: "가",
    prompt: "장난감의 가_이 비싸요.",
    answer: "ㅄ",
    choices: ["ㅂ", "ㅄ", "ㄳ", "ㅅ"],
    hint: "가격을 뜻해요."
  },
  {
    id: "5-2-09",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "넓다",
    stem: "너",
    prompt: "운동장이 아주 너_다.",
    answer: "ㄼ",
    choices: ["ㅂ", "ㄼ", "ㄺ", "ㄻ"],
    hint: "좁다의 반대예요."
  },
  {
    id: "5-2-10",
    world: 5,
    stage: 2,
    type: "sentence",
    word: "싫다",
    stem: "시",
    prompt: "나는 거짓말이 시_다.",
    answer: "ㅀ",
    choices: ["ㅎ", "ㅀ", "ㄾ", "ㄿ"],
    hint: "좋아하지 않는다는 뜻이에요."
  },
  {
    id: "5-3-01",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "닭",
    choices: ["달", "닭", "닥"],
    hint: "꼬끼오 하고 우는 동물이에요.",
    audioSrc: "/audio/5-3-01.mp3",
    audioText: "닭이 마당을 걸어 다녀요."
  },
  {
    id: "5-3-02",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "향기가 나요.",
    audioSrc: "/audio/5-3-02.mp3",
    audioText: "꽃이 활짝 피었어요."
  },
  {
    id: "5-3-03",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요.",
    audioSrc: "/audio/5-3-03.mp3",
    audioText: "물건의 값이 비싸요."
  },
  {
    id: "5-3-04",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "밭",
    choices: ["밧", "밭", "받"],
    hint: "농작물을 심는 곳이에요.",
    audioSrc: "/audio/5-3-04.mp3",
    audioText: "밭에 감자를 심었어요."
  },
  {
    id: "5-3-05",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고"],
    hint: "책을 보는 행동이에요.",
    audioSrc: "/audio/5-3-05.mp3",
    audioText: "책을 읽고 있어요."
  },
  {
    id: "5-3-06",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "안의 반대예요.",
    audioSrc: "/audio/5-3-06.mp3",
    audioText: "밖에서 친구가 기다리고 있어요."
  },
  {
    id: "5-3-07",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "맑아요",
    choices: ["막아요", "맑아요", "말아요"],
    hint: "구름이 적고 깨끗한 상태예요.",
    audioSrc: "/audio/5-3-07.mp3",
    audioText: "오늘은 하늘이 맑아요."
  },
  {
    id: "5-3-08",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "공",
    choices: ["곰", "공", "곤"],
    hint: "둥근 놀이 도구예요.",
    audioSrc: "/audio/5-3-08.mp3",
    audioText: "강아지가 공을 가지고 놀아요."
  },
  {
    id: "5-3-09",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "싫어요",
    choices: ["실어요", "싫어요", "싯어요"],
    hint: "좋아하지 않는다는 뜻이에요.",
    audioSrc: "/audio/5-3-09.mp3",
    audioText: "나는 거짓말이 싫어요."
  },
  {
    id: "5-3-10",
    world: 5,
    stage: 3,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "몫",
    choices: ["목", "몫", "못"],
    hint: "나누어 받은 자기 부분이에요.",
    audioSrc: "/audio/5-3-10.mp3",
    audioText: "각자 자기 몫을 가져가세요."
  },
  {
    id: "5-4-01",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "물건의 갑이 너무 비싸요. 바른 말을 고르세요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요.",
    correctSentence: "물건의 값이 너무 비싸요."
  },
  {
    id: "5-4-02",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "나는 책을 익고 있어요. 바른 말을 고르세요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고"],
    hint: "책을 보는 행동이에요.",
    correctSentence: "나는 책을 읽고 있어요."
  },
  {
    id: "5-4-03",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "꽃이 밧에 피었어요. 바른 말을 고르세요.",
    answer: "밭에",
    choices: ["밧에", "밭에", "받에"],
    hint: "농작물을 심는 땅이에요.",
    correctSentence: "꽃이 밭에 피었어요."
  },
  {
    id: "5-4-04",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "친구가 박에서 기다려요. 바른 말을 고르세요.",
    answer: "밖에서",
    choices: ["박에서", "밖에서", "밬에서"],
    hint: "안의 반대예요.",
    correctSentence: "친구가 밖에서 기다려요."
  },
  {
    id: "5-4-05",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "각자 자기 목을 가져가세요. 바른 말을 고르세요.",
    answer: "몫",
    choices: ["목", "몫", "못"],
    hint: "나누어 받은 자기 부분이에요.",
    correctSentence: "각자 자기 몫을 가져가세요."
  },
  {
    id: "5-4-06",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "새 옺을 입었어요. 바른 말을 고르세요.",
    answer: "옷",
    choices: ["옷", "옺", "옻"],
    hint: "몸에 입어요.",
    correctSentence: "새 옷을 입었어요."
  },
  {
    id: "5-4-07",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "낫에는 해가 떠 있어요. 바른 말을 고르세요.",
    answer: "낮",
    choices: ["낫", "낮", "낯"],
    hint: "밤의 반대예요.",
    correctSentence: "낮에는 해가 떠 있어요."
  },
  {
    id: "5-4-08",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "나뭇입이 떨어졌어요. 바른 말을 고르세요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무의 부분이에요.",
    correctSentence: "나뭇잎이 떨어졌어요."
  },
  {
    id: "5-4-09",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "햇빗이 따뜻해요. 바른 말을 고르세요.",
    answer: "빛",
    choices: ["빗", "빛", "빚"],
    hint: "밝게 비추는 것이에요.",
    correctSentence: "햇빛이 따뜻해요."
  },
  {
    id: "5-4-10",
    world: 5,
    stage: 4,
    type: "fix-spelling",
    prompt: "너븐 운동장에서 놀았어요. 바른 말을 고르세요.",
    answer: "넓은",
    choices: ["너븐", "넓은", "널은"],
    hint: "좁은의 반대예요.",
    correctSentence: "넓은 운동장에서 놀았어요."
  },
  {
    id: "5-5-01",
    world: 5,
    stage: 5,
    type: "image",
    word: "꽃",
    stem: "꼬",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㅊ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "향기가 나요.",
    imageHint: "꽃 그림"
  },
  {
    id: "5-5-02",
    world: 5,
    stage: 5,
    type: "sentence",
    word: "밭",
    stem: "바",
    prompt: "감자를 바_에 심었어요.",
    answer: "ㅌ",
    choices: ["ㄷ", "ㅅ", "ㅈ", "ㅌ"],
    hint: "농작물을 기르는 땅이에요."
  },
  {
    id: "5-5-03",
    world: 5,
    stage: 5,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "읽고",
    choices: ["익고", "읽고", "일고"],
    hint: "책을 보는 행동이에요.",
    audioSrc: "/audio/5-5-03.mp3",
    audioText: "책을 읽고 있어요."
  },
  {
    id: "5-5-04",
    world: 5,
    stage: 5,
    type: "fix-spelling",
    prompt: "박에 비가 와요. 바른 말을 고르세요.",
    answer: "밖",
    choices: ["박", "밖", "밬"],
    hint: "안의 반대예요.",
    correctSentence: "밖에 비가 와요."
  },
  {
    id: "5-5-05",
    world: 5,
    stage: 5,
    type: "word-choice",
    word: "낮",
    prompt: "해가 떠 있는 시간을 고르세요.",
    answer: "낮",
    choices: ["낫", "낮", "낯", "낱"],
    hint: "밤의 반대예요."
  },
  {
    id: "5-5-06",
    world: 5,
    stage: 5,
    type: "sentence",
    word: "값",
    stem: "가",
    prompt: "이 장난감의 가_은 오천 원이에요.",
    answer: "ㅄ",
    choices: ["ㅂ", "ㅄ", "ㄳ", "ㅅ"],
    hint: "가격을 뜻해요."
  },
  {
    id: "5-5-07",
    world: 5,
    stage: 5,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "맑아요",
    choices: ["막아요", "맑아요", "말아요"],
    hint: "구름이 적고 깨끗한 상태예요.",
    audioSrc: "/audio/5-5-07.mp3",
    audioText: "오늘은 하늘이 맑아요."
  },
  {
    id: "5-5-08",
    world: 5,
    stage: 5,
    type: "fix-spelling",
    prompt: "나뭇입이 바람에 흔들려요. 바른 말을 고르세요.",
    answer: "잎",
    choices: ["입", "잎", "잇"],
    hint: "나무의 부분이에요.",
    correctSentence: "나뭇잎이 바람에 흔들려요."
  },
  {
    id: "5-5-09",
    world: 5,
    stage: 5,
    type: "word-choice",
    word: "싫다",
    prompt: "좋아하지 않는다는 뜻의 말을 고르세요.",
    answer: "싫다",
    choices: ["실다", "싫다", "싯다", "실타"],
    hint: "ㅀ 받침이에요."
  },
  {
    id: "5-5-10",
    world: 5,
    stage: 5,
    type: "sentence",
    word: "넓다",
    stem: "너",
    prompt: "운동장이 아주 너_다.",
    answer: "ㄼ",
    choices: ["ㅂ", "ㄼ", "ㄺ", "ㄻ"],
    hint: "좁다의 반대예요."
  },
  {
    id: "5-5-11",
    world: 5,
    stage: 5,
    type: "image",
    word: "닭",
    stem: "다",
    prompt: "그림을 보고 단어를 완성하세요.",
    answer: "ㄺ",
    choices: ["ㄱ", "ㄺ", "ㄻ", "ㄼ"],
    hint: "꼬끼오 하고 울어요.",
    imageHint: "닭 그림"
  },
  {
    id: "5-5-12",
    world: 5,
    stage: 5,
    type: "sentence",
    word: "빛",
    stem: "비",
    prompt: "햇비_이 창문으로 들어와요.",
    answer: "ㅊ",
    choices: ["ㅅ", "ㅈ", "ㅊ", "ㄷ"],
    hint: "밝게 비추는 것이에요."
  },
  {
    id: "5-5-13",
    world: 5,
    stage: 5,
    type: "audio",
    prompt: "들은 문장에 나온 단어를 고르세요.",
    answer: "값",
    choices: ["갑", "값", "갓"],
    hint: "가격을 뜻해요.",
    audioSrc: "/audio/5-5-13.mp3",
    audioText: "물건의 값이 비싸요."
  },
  {
    id: "5-5-14",
    world: 5,
    stage: 5,
    type: "fix-spelling",
    prompt: "화단에 꼿이 피었어요. 바른 말을 고르세요.",
    answer: "꽃",
    choices: ["꼿", "꽃", "꼳"],
    hint: "봄에 많이 볼 수 있어요.",
    correctSentence: "화단에 꽃이 피었어요."
  },
  {
    id: "5-5-15",
    world: 5,
    stage: 5,
    type: "audio",
    prompt: "들은 문장에서 바른 말을 고르세요.",
    answer: "싫어요",
    choices: ["실어요", "싫어요", "싯어요"],
    hint: "좋아하지 않는다는 뜻이에요.",
    audioSrc: "/audio/5-5-15.mp3",
    audioText: "나는 거짓말이 싫어요."
  },
];
