import type { GameState,Question } from '../../types/game';
import { AudioPlayerButton } from './AudioPlayerButton';
import { AnswerButton } from './AnswerButton';
import { getAnswerInstruction } from '../../lib/question-ui';
export function GameCard({question,state,onAnswer,onHint,onNext}:{question:Question;state:GameState;onAnswer:(choice:string)=>void;onHint:()=>void;onNext:()=>void}){
  const feedback=state.feedback;
  const typeLabel={batchim:'받침을 골라요',sentence:'문장 속 단서',image:'그림 속 단어',audio:'소리를 들어요','word-choice':'단어를 골라요','fix-spelling':'맞춤법을 고쳐요'}[question.type];
  return <section className="game-card"><div className="game-card-label"><span className="pill muted">{question.world===7?'한자를 읽어요':typeLabel}</span><span>{state.round?`재구조 ${state.round} / 2`:state.index===state.total-1?(question.world===5&&question.stage===5?'🚨 최종 구조 임무':'🚨 긴급 구조 문제'):`MISSION ${String(state.index+1).padStart(2,'0')}`}</span></div>{question.type==='image'&&<div className="question-image" role="img" aria-label={question.hint}>{question.image}</div>}<h2 className={`question-text ${question.type==='sentence'?'sentence-question':''}`}>{question.question}</h2>{['batchim','image'].includes(question.type)&&<div className="question-word">{feedback?.correct?question.word:question.stem}</div>}{question.type==='audio'&&!feedback&&<AudioPlayerButton key={question.id} src={question.audioSrc}/>}<p className="answer-instruction">{question.world===7?'한자의 음과 뜻을 함께 읽고 알맞은 답을 선택해 주세요.':question.world===6?'뜻과 문맥에 알맞은 표현을 선택해 주세요.':getAnswerInstruction(question.answer)}</p><div className="answer-grid">{question.choices.map((c,i)=><AnswerButton key={c} choice={c} index={i} selected={feedback?.choice===c} correct={feedback?.correct??null} disabled={Boolean(feedback)} onClick={()=>onAnswer(c)}/>)}</div><div className="hint-area">{!feedback&&<button className="hint-button" disabled={state.hinted} onClick={onHint}>💡 {state.hinted?'힌트를 확인했어요':'힌트 보기 · −20점'}</button>}{state.hinted&&!feedback&&<p className="hint-text">{question.hint}</p>}</div>{feedback&&<div className={`feedback-box ${feedback.correct?'success-box':'retry-box'}`} role="status"><div><strong>{feedback.correct?'✓ 구조 성공!':'앗! 다시 생각해 봐요.'}</strong>{feedback.correct&&<b>+{feedback.points}점</b>}</div><p>{question.explanation}</p>{!feedback.correct&&<small>괜찮아요! 잠시 뒤 재구조 임무에서 다시 만나요.</small>}<button className="button" onClick={onNext}>{state.index+1===state.queue.length?(state.pending.length&&state.round<2?'재구조 임무로 →':'결과 확인하기 →'):'다음 문제 →'}</button></div>}</section>;
}


